### ISSUE TITLE
Dutch language by AntoineH

### ISSUE THREAD

**Issue by AntoineH1987** [DanTheMan827/uTikDownloadHelper#1]
**Title ID**
Titel ID

**Name**
Naam

**Region**
Regio

**Title Size**
Titel groote

**Update Size**
Update groote

**Download Selected**
Download geselecteerden

**Open Ticket**
Ticket openen

**Current File**
Huidig bestand

**Transfer Rate**
Download Snelheid

**Average Rate**
Gemiddelde snelheid

**Title**
Titel

**Update**
Update

**Download**
Download

**What is the address of this website?**
Wat is het adres van deze website?

**The Wii U Title Key Database**
De Wii U titel key database

**Just type the hostname, e.g: abc.xyz.com**
Typ de website, bijvoorbeeld: abc.xyz.com

**Answer this question**
Beantwoord deze vraag

**Downloading Title Metadata**
Downloaden titel metadata

**The following titles encountered an error**
Bij deze titels is een fout opgetreden

**The following title encountered an error**
Bij deze titel is een fout opgetreden

**Downloads completed successfully**
Downloads succesvol afgerond

**Download completed successfully**
Download succesvol afgerond

**Success**
Succes

**There are currently downloads in progress, do you want to cancel them?**
Er worden bestanden gedownload, wilt u deze annuleren?

**Downloads in Progress**
Bezig met downloaden

**Download in Progress**
Bezig met downloaden

**Repair complete**
Reparatie compleet

**Repair failed**
Reparatie mislukt

**What type of content do you want to download?**
Welk type inhoud wilt u downloaden?

**Game**
Spel

**Patch**
Patch

**Both**
Beide

**Time Remaining**
Resterende Tijd

**Want automatic ticket fetching?**
Wilt u automatisch de tickets ophalen?

**Answer this question to enable it.**
Beantwoord deze vraag om te kunnen gebruiken.

**Loading Data...**
Data Laden...

**Do you want to delete the incomplete files?**
Wilt u de incomplete bestanden verwijderen?

**Incomplete Files**
Incomplete Bestanden

**Unable to contact the title key website.**
Kan geen verbinding maken met de title key website.

**You are currently viewing data that was cached the last time the application was run.**
U bekijkt momenteel de gegevens van de laatste keer dat de applicatie werd uitgevoerd.

**Select Content Type**
Selecteer type inhoud.

**Comment by DanTheMan827** [comment]
Could you also provide a translation for "Time Remaining"

**Comment by DanTheMan827** [comment]
So, I forgot some in the initial list...

- Want automatic ticket fetching?
- Answer this question to enable it.
- Loading Data...

**Comment by DanTheMan827** [comment]
and...
 
- Do you want to delete the incomplete files?
- Incomplete Files

**Comment by AntoineH1987** [comment]
I have edit the list with the new words.

**Comment by DanTheMan827** [comment]
thanks

**Comment by AntoineH1987** [comment]
The list is updated
