### ISSUE TITLE
question:how do i use this for dlc

### ISSUE THREAD

**Issue by monkeyman4412** [DanTheMan827/uTikDownloadHelper#11]
sorry to ask this, but how do you use it for dlc, any mini tutorial i can follow for that please. because i recive a error when using wup installer y, its claiming title tick is not correct... 
edit what its saying "error:install code 0xfffbf442
verfiy title.tik and wup files are correct and complete" 
It might be my end im going to try a few more times

**Comment by esmilodonte** [comment]
i had the same error. I think the red ones on the list, only can be installed by the rednand method, that include the DLC. If you can install by the simple method the DLC and the titles in red, please advice. Saludos from Margarita Island, Venezuela.

**Comment by DanTheMan827** [comment]
That's correct, the ones in red require redNAND
