### ISSUE TITLE
Trouble with the uTik browser

### ISSUE THREAD

**Issue by utlk** [DanTheMan827/uTikDownloadHelper#14]
After typing in _that_ website. I get this error and the browser doesn't load.

Unexpected Character Encounter while parsing value <. Path". line 0, position 0.

I can still use it to download from title cards on my computer, but id still appreciate it if I could know a fix for this.

**Comment by DanTheMan827** [comment]
The address is not the ISO site, it's something else

**Comment by utlk** [comment]
the website urls i used only allowed me to download title files, not isos. Unless im missunderstanding.

**Comment by utlk** [comment]
Im an idiot, problem is fixed.
