### ISSUE TITLE
Spanish Languague by Panamex

### ISSUE THREAD

**Issue by panamex** [DanTheMan827/uTikDownloadHelper#2]
**Title ID**
Título ID

**Name**
Nombre

**Region**
Región

**Title Size**
Tamaño del Título

**Update Size**
Tamaño de la Actualización

**Download Selected**
Descarga Seleccionada

**Open Ticket**
Abrir Etiqueta

**Current File**
Archivo Actual

**Transfer Rate**
Tasa de Transferencia

**Average Rate**
Tasa Promedio

**Title**
Título

**Update**
Actualizaciòn

**Download**
Descarga

**What is the address of this website?**
Cuàl es la direcciòn de este sitio web?

**The Wii U Title Key Database**
La Base de Datos de Títulos Clave de Wii U

**Just type the hostname, e.g: abc.xyz.com**
Sólo escriba el nombre del host, por ejemplo: abc.xyz.com

**Answer this question**
Responda a esta pregunta

**Downloading Title Metadata**
Descargando los Metadatos de los Títulos

**The following titles encountered an error**
Los siguientes títulos encontraron un error

**The following title encountered an error**
El siguiente título encontró un error

**Downloads completed successfully**
Descargas completadas exitosamente

**Download completed successfully**
Descarga completada existosamente

**Success**
Éxito

**There are currently downloads in progress, do you want to cancel them?**
Actualmente hay descargas en progreso, quiere cancelarlos?

**Downloads in Progress**
Descargas en Progreso

**Download in Progress**
Descarga en Progreso

**Repair complete**
Reparaciòn completada

**Repair failed**
Reparaciòn fallida 

**What type of content do you want to download?**
Qué tipo de contenido quieres descargar?

**Game**
Juego

**Patch**
Parche

**Both**
Ambos

**Time Remaining**
Tiempo Restante

**Comment by DanTheMan827** [comment]
Could you also provide a translation for "Time Remaining"

**Comment by panamex** [comment]
Tiempo Restante



________________________________
De: DanTheMan827 <notifications@github.com>
Enviado: lunes, 31 de octubre de 2016 12:18:05 p. m.
Para: DanTheMan827/uTikDownloadHelper
Cc: panamex; Author
Asunto: Re: [DanTheMan827/uTikDownloadHelper] Spanish Languague by Panamex (#2)


Could you also provide a translation for "Time Remaining"

-

**Comment by DanTheMan827** [comment]
So, I forgot some in the initial list...

- Want automatic ticket fetching?
- Answer this question to enable it.
- Loading Data...

**Comment by DanTheMan827** [comment]
and...
 
- Do you want to delete the incomplete files?
- Incomplete Files

**Comment by panamex** [comment]
*   Do you want to delete the incomplete files?             Desea borrar los archivos incompletos?
  *   Incomplete Files                                                              Archivos incompletos
  *   Want automatic ticket fetching?                                  Desea búsqueda automatica de etiqueta?
  *   Answer this question to enable it.                               Responda esta pregunta para habilitarlo.
  *   Loading Data.                                                                   Cargando Datos.


________________________________
De: DanTheMan827 <notifications@github.com>
Enviado: lunes, 31 de octubre de 2016 08:42:13 p. m.
Para: DanTheMan827/uTikDownloadHelper
Cc: panamex; Author
Asunto: Re: [DanTheMan827/uTikDownloadHelper] Spanish Languague by Panamex (#2)


and...

  *   Do you want to delete the incomplete files?
  *   Incomplete Files

-

**Comment by DanTheMan827** [comment]
Could I get a couple more?

- Unable to contact the title key website.
- You are currently viewing data that was cached the last time the application was run.
- Select Content Type

**Comment by kakamerci** [comment]
Unable to contact the title key website.
Incapaz de contactar el sitio del título clave.
       
You are currently viewing data that was cached the last time the application was run.
Actualmente estás viendo la data que fue almacenado en cache la última vez que la aplicación se ejecutó.

Select Content Type
Selecciona el Tipo de Contenido
