### ISSUE TITLE
French Language by MockyLock

### ISSUE THREAD

**Issue by DanTheMan827** [DanTheMan827/uTikDownloadHelper#3]
**Title ID**
Titre ID

**Name**
Nom

**Region**
Région

**Title Size**
Taille du titre

**Update Size**
Mise à jour de la taille

**Download Selected**
Télécharger la sélection

**Open Ticket**
Ouvrir un Ticket

**Current File**
Fichier actuel

**Transfer Rate**
Taux de transfert

**Average Rate**
Taux moyen

**Title**
Titre

**Update**
Mise à jour

**Download**
Téléchargement

**What is the address of this website?**
Quelle est l'adresse de ce site ?

**The Wii U Title Key Database**
La base de données des clées des titres WiiU

**Just type the hostname, e.g: abc.xyz.com**
Entrez seulement le nom du site, ex: abc.xyz.com

**Answer this question**
Répondez à cette question

**Downloading Title Metadata**
Téléchargement du Metadata du titre

**The following titles encountered an error**
Les titres suivant ont rencontré une erreur

**The following title encountered an error**
Le titre suivant a rencontré une erreur

**Downloads completed successfully**
Téléchargements terminés avec succès

**Download completed successfully**
Téléchargement terminé avec succès

**Success**
Succès

**There are currently downloads in progress, do you want to cancel them?**
Il y a actuellement des téléchargements en cours, voulez-vous les annuler ?

**Downloads in Progress**
Téléchargements en cours

**Download in Progress**
Téléchargement en cours

**Repair complete**
Réparation terminée

**Repair failed**
Réparation échouée

**What type of content do you want to download?**
Quel type de contenu voulez-vous télécharger ?

**Game**
Jeu

**Patch**
Patch

**Both**
Les deux

**Time remaining**
Temps restant

**Comment by Meumeu33160** [comment]
Hey hello. I find some mistakes in this translation and I would like to help.
*"Title ID" should be "ID du titre" or "Identifiant Titre" to be clearer. We can't say "Titre ID", it's like saying "ID Title" in English.

*Wrong translation for "Update Size". The right translation should be "Taille de la mise à jour" and not
"Mise à jour de la taille" (which is the equivalent of "Size update").

*Approximate translation for "Downloading Title Metadata"
The good one should be : "Téléchargement des métadonnées du titre". In French, we don't say metadata and we use the plural.

*The following titles encountered an error :
"Les titres suivantS ont rencontré une erreur" (an "s" is missing to respect the use of the plural)

The other translations seem fine to me. =)

**Comment by DanTheMan827** [comment]
@Meumeu33160 

Would you mind translating these?

- Unable to contact the title key website.
- You are currently viewing data that was cached the last time the application was run.
- Select Content Type

**Comment by Meumeu33160** [comment]
@DanTheMan827 
No problem :

Unable to contact the title key website.
= Impossible d'accéder au site de clés de titres
You are currently viewing data that was cached the last time the application was run.
= Vous voyez actuellement les données gardées en cache au dernier lancement de l'application.
Select Content Type
=Sélectionnez le type de contenu

By the way, I tried to translate this not too literally because it would sound weird in French. In each language we have typical words and sentences that users have the habit to see in softwares. But well, without context I can't  do much more.
