### ISSUE TITLE
Italian translation by Ryccardo

### ISSUE THREAD

**Issue by rboninsegna** [DanTheMan827/uTikDownloadHelper#4]
**Title ID**
Title ID

**Name**
Titolo

**Region**
Regione

**Title Size**
Dimensione app

**Update Size**
Dim. aggiornamento

**Download Selected**
Scarica selezionati

**Open Ticket**
Apri file ticket

**Current File:**
File in corso:

**Transfer Rate:**
Velocità:

**Average Rate:**
Vel. media:

**Title**
Gioco

**Update**
Aggiornamento

**Download**
Scarica

**What is the address of this website?**
Indirizzo di questo sito web?

**The Wii U Title Key Database**
The Wii U Title Key Database _(it's a name that most people will google, I don't think it should be translated)_

**Just type the hostname, e.g: abc.xyz.com**
Scrivi solo il dominio nel formato abc.xyz.com

**Answer this question**
Rispondi alla domanda

**Downloading Title Metadata**
Scaricamento metadati titoli

**The following titles encountered an error**
Errore per i seguenti titoli

**The following title encountered an error**
Errore per il seguenti titolo

**Downloads completed successfully**
Download completati

**Download completed successfully**
Download completato

**Success**
Successo

**There are currently downloads in progress, do you want to cancel them?**
Ci sono download in corso, vuoi annullarli?

**Downloads in Progress**
Download in corso

**Download in Progress**
Download in corso _(yes, the same)_

**Repair complete**
Riparazione completata

**Repair failed**
Riparazione fallita

**What type of content do you want to download?**
Che tipo di contenuto vuoi scaricare?

**Game**
Gioco

**Patch**
Aggiornamento

**Both**
Entrambi

**Time Remaining:**
Tempo residuo:

**Comment by DanTheMan827** [comment]
Thanks

Yeah, now that you mention it maybe I shouldn't translate the site name...

**Comment by DanTheMan827** [comment]
So, I forgot some in the initial list...

- Want automatic ticket fetching?
- Answer this question to enable it.
- Loading Data...

**Comment by DanTheMan827** [comment]
and...
 
- Do you want to delete the incomplete files?
- Incomplete Files

**Comment by rboninsegna** [comment]
**Want automatic ticket fetching?**
Vuoi scaricare automaticamente i ticket?
**Answer this question to enable it.**
Rispondi a questa domanda per attivarlo _(assuming it's for the previous question)_
**Loading Data...**
Caricamento dati...
**Do you want to delete the incomplete files?**
Vuoi eliminare i file incompleti?
**Incomplete Files**
File incompleti

**Comment by DanTheMan827** [comment]
Could I get a couple more?

- Unable to contact the title key website.
- You are currently viewing data that was cached the last time the application was run.
- Select Content Type

**Comment by rboninsegna** [comment]
In order:

Impossibile contattare il sito delle titlekey.

Sono visualizzati i dati scaricati durante un'esecuzione precedente.

Seleziona tipo di contenuto
