### ISSUE TITLE
What .NET does this program use ?

### ISSUE THREAD

**Issue by azoreseuropa** [DanTheMan827/uTikDownloadHelper#41]
I am trying to use it with wineskin for my macOS. Unless, compile is possible ?

**Comment by azoreseuropa** [comment]
Hello ??

**Comment by DanTheMan827** [comment]
It uses .net 4.5 and doesn't work under wine

**Comment by azoreseuropa** [comment]
Is there a way you can compile it for MacOS users ? :)

**Comment by azoreseuropa** [comment]
Hello ?

**Comment by DanTheMan827** [comment]
Compiling it for Mac OS X would require a rewrite since it doesn't work with Wine.

**Comment by azoreseuropa** [comment]
Thank you.
