### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by bkifft** [DanTheMan827/uTikDownloadHelper#6]
edit: meh, shouldn't have filtered for the localization label ;)
Formal-ish version:

**Title ID**
Titel ID

**Name**
Name

**Region**
Region

**Title Size**
Titel Größe

**Update Size**
Aktualisierungs Größe

**Download Selected**
Auswahl herunterladen

**Open Ticket**
Ticket öffnen

**Want automatic ticket fetching?**
Sollen Tickets automatisch heruntergeladen werden?

**Answer this question to enable it.**
Beantworten Sie diese Frage um es zu ermöglichen. 

**Loading Data...**
Lade Daten...

**Current File:**
Aktuelle Datei:

**Transfer Rate:**
Aktuelle Übertragungsrate:

**Average Rate:**
Mittlere Übertragungsrate:

**Time Remaining:**
Verbleibende Zeit:

**Title**
Titel

**Update**
Aktualisierung

**Download**
Herunterladen

**What is the address of this website?**
Was ist die Adresse dieser Website?

**Just type the hostname, e.g: abc.xyz.com**
Geben Sie einfach den Hostnamen ein, z.B. abc.xyz.com

**Answer this question**
Beantworten Sie diese Frage

**Downloading Title Metadata**
Lade Titel Metadaten herunter.

**The following titles encountered an error**
Bei den folgenden Titeln gab es einen Fehler

**The following title encountered an error**
Bei dem folgenden Titel gab es einen Fehler

**Downloads completed successfully**
Herunterladen erfolgreich abgeschlossen

**Download completed successfully**
Herunterladen erfolgreich abgeschlossen

**Success**
Erfolg

**There are currently downloads in progress, do you want to cancel them?**
Es werden aktuell Daten heruntergeladen, soll dies abgebrochen werden?

**Downloads in Progress**
Es wird heruntergeladen

**Download in Progress**
Es wird heruntergeladen

**Repair complete**
Reperatur abgeschlossen

**Repair failed**
Reperatur fehlgeschlagen

**What type of content do you want to download?**
Welche Art von Inhalten wollen Sie herunterladen?

**Game**
Spiel

**Patch**
Aktualisierung

**Both**
Beides

**Comment by DanTheMan827** [comment]
I think I might actually use yours since some of the phrases would fit inside the buttons and labels a little better....

But... could I get a couple more translations?

- Unable to contact the title key website.
- You are currently viewing data that was cached the last time the application was run.
- Select Content Type

**Comment by bkifft** [comment]
- Unable to contact the title key website.
Die Titel Schlüssel Website ist nicht erreichbar.

- You are currently viewing data that was cached the last time the application was run.
Sie sehen aktuell Daten, die noch von der letzten Ausführung dieser Anwendung gespeichert sind.

- Select Content Type
Inhaltstyp auswählen
