### ISSUE TITLE
New Update feature downloads incomplete update files

### ISSUE THREAD

**Issue by dyerseve** [DanTheMan827/uTikDownloadHelper#9]
Using 2.2.0 utikdownloader, updates are missing some h3 files, the result is installing them with wupinstaller y mod 1.2.1 produces this error at about the 50MB mark:
Error: 0xFFFCFFE9 access failed

I had been downloading updates with jnustool prior to this and checked it's results versus your tool and for example Star Fox Zero v16 is missing 00000010.h3 and 00000011.h3, everything else has matching checksums though.

**Comment by dyerseve** [comment]
Also tested NES Remix and 00000011.h3 is missing, Star Fox Guard works fine (doesn't have 10 or 11), but then Mighty No. 9 is missing 00000011.h3 as well.

**Comment by DanTheMan827** [comment]
I just tested it using the latest version that was just released...

While I didn't specifically fix anything relating to updates I did fix another bug that could have possibly contribute towards it...

Every game you mentioned I just tested and all of the missing files you mentioned were downloaded...

So give this one a shot and see if it works!

**Comment by Gerard2003** [comment]
Now you should close this issue right?

**Comment by dyerseve** [comment]
Might have been user error, I still had 2 dlls in the utik folder from an older version, I removed those and now it works fine.

**Comment by DanTheMan827** [comment]
that would do it...

libNUS.dll was an old version of the library I made to get file URLs for the game content and that specific one had a bug that made it not provide h3 files for some content...

I've always tried to keep those embedded inside the exe but that one slipped...
